# Generated by Django 5.1.6 on 2025-02-12 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('phone', models.TextField(max_length=100, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=200, verbose_name='Correo')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('tour', models.CharField(max_length=200, verbose_name='Tours')),
                ('adults', models.CharField(max_length=100, verbose_name='Adultos')),
                ('air', models.CharField(max_length=200, verbose_name='Aerolinea')),
                ('nair', models.CharField(max_length=200, verbose_name='numero de vuelo')),
                ('air_r', models.CharField(default='None', max_length=200, verbose_name='Aerolinea retorno')),
                ('nair_r', models.CharField(default='None', max_length=200, verbose_name='numero de vuelo retorno')),
                ('origen', models.CharField(default='null', max_length=200, verbose_name='Origen')),
                ('destino', models.CharField(default='null', max_length=200, verbose_name='Destino')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('checkin', models.DateField(default=0, verbose_name='Checkin')),
                ('origen_ret', models.CharField(default='null', max_length=200, verbose_name='Origen de retorno')),
                ('destino_ret', models.CharField(default='Null', max_length=200, verbose_name='Destino de retorno')),
                ('date_ret', models.DateField(default=0, verbose_name='Fecha de retorno')),
                ('hora_ret', models.TimeField(default=0, verbose_name='Hora de retorno')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('opcion', models.CharField(default='null', max_length=100, verbose_name='Opcion')),
                ('recorrido', models.CharField(default='null', max_length=100, verbose_name='Recorrido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
            ],
        ),
    ]
