# Generated by Django 5.1.6 on 2025-02-08 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculosVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo')),
                ('Number_passengers', models.IntegerField(default=0, verbose_name='Cantidad de pasajeros')),
                ('amount_luggage', models.IntegerField(default=0, verbose_name='Cantidad de equipaje')),
                ('image', models.ImageField(default='null', upload_to='vehiculos_vip', verbose_name='Imagen')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vehiculo VIP',
                'verbose_name_plural': 'Vehiculos VIP',
                'ordering': ['order'],
            },
        ),
    ]
